[package]
name = "p42-arithmetic-kakeya-objective-script"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
hex.workspace = true
p42-arithmetic-kakeya-objective-core = { path = "../core" }
sp1-sdk.workspace = true

[build-dependencies]
sp1-build.workspace = true
