import type { Metadata } from "next";
import Link from "next/link";
import { MathBlock, MathInline } from "@/components/Math";
import { PackingLab, Reveal, VerifierSwitch } from "@/components/ProtocolJourney";
import { sitePath } from "@/lib/site-paths";

export const metadata: Metadata = {
  title: "Journey — Why P42 Exists",
  description: "The records, failed searches, exact certificates, and adversarial lessons that became the P42 protocol.",
  alternates: { canonical: sitePath("/journey") },
  openGraph: { title: "Journey — Why P42 Exists", description: "From the arena to an open settlement layer for mathematical truth.", images: [{ url: sitePath("/story/hero-hand-to-sand.webp"), width: 1680, height: 945 }] },
};

export default function FromHandToSandPage() {
  return <article className="journey">
    <header className="journey-hero">
      <div className="journey-hero-copy"><p className="kicker">The origin of the protocol · July 2026</p><h1>Journey</h1><p className="journey-deck">Machines can now produce frontier mathematics. The harder question is whether anyone can trust what they produce. This is the story of the records, failures, exploits, and exact certificates that became P42.</p><a className="journey-scroll" href="#invitation">Enter the story <span>↓</span></a></div>
      <figure className="journey-hero-art"><img src={sitePath("/story/hero-hand-to-sand.webp")} alt="A hand holding a prize check dissolves into grains that form an exact geometric structure."/><figcaption>The pocket check becomes a protocol.</figcaption></figure>
    </header>

    <section className="journey-opening" id="invitation"><p className="journey-dropcap">Paul Erdős used to carry his prizes in his pocket.</p><p>He wandered between universities with a suitcase, posed a problem, and attached a number to it—payable from his own wallet to whoever solved it. No committee. No gatekeeper. The proof was the settlement rule.</p><p>The money was never the point. The <em>protocol</em> was the point: a trust layer between an open problem and anyone, anywhere, audacious enough to attack it.</p><aside className="journey-margin-note">Erdős died in 1996. His problems outlived him. The protocol waited.</aside></section>

    <Reveal><section className="journey-chapter"><div className="journey-chapter-no">01</div><div className="journey-copy"><p className="kicker">The arena</p><h2>We learned how mathematical claims fail.</h2><p>CHRONOS spent months attacking live optimization problems: kissing numbers, autocorrelation inequalities, prime-counting functionals, and the Erdős minimum-overlap constant. We won boards. We lost boards. The leaderboard was the least valuable thing we found there.</p><p>Our first apparent minimum-overlap win exploited a rescaling step the scorer did not check tightly enough. We refused to submit it. Weeks later, the honest construction became the first proven improvement of the upper bound since 2016.</p></div><blockquote className="journey-law">Certified<br/>beats float.</blockquote></section></Reveal>

    <section className="certificate-theorem"><div><span className="smallcaps">The certified path</span><h2>A claim is not its score.</h2><p>The search may use approximations. The published claim does not. A plain checker reconstructs the result from raw rational data and verifies every constraint independently.</p></div><div className="certificate-equations"><MathBlock tex={String.raw`x_i \in \mathbb{Q}^d,\qquad \lVert x_i\rVert^2 = 1`}/><MathBlock tex={String.raw`\langle x_i,x_j\rangle \le \alpha \quad (i\ne j)`}/><div className="exact-arrow">search proposes <span>→</span> exact arithmetic decides</div></div></section>

    <Reveal><section className="journey-chapter journey-chapter-wide"><div className="journey-chapter-no">02</div><div className="journey-copy"><p className="kicker">Ninety-plus rounds</p><h2>The week we hunted a world record.</h2><p>The kissing number <MathInline tex="K(d)"/> asks how many unit spheres can touch a central one in dimension <MathInline tex="d"/>. In eleven dimensions, the record was 604. We rebuilt it exactly and found its hidden symmetry: each point has a mirror twin.</p><MathBlock tex={String.raw`X=-X,\qquad |X|=604\quad\Longrightarrow\quad 302\text{ lines through }0`}/><p>Geometry became combinatorics. Search became decision. Exact methods proved that no 605th sphere hides inside that architecture—gap zero.</p></div></section></Reveal>

    <section className="packing-section"><div className="packing-intro"><span className="smallcaps">Interactive plate · projection, not proof</span><h2>You cannot gradient-descend into a combinatorial crystal.</h2><p>Move between the three lenses. The visual projection teaches the structural difference; the certificate carries the proof.</p></div><PackingLab/></section>
    <figure className="journey-image-break"><img loading="lazy" src={sitePath("/story/combinatorial-crystal.webp")} alt="An antipodal mathematical crystal repels smooth optimization contours."/><figcaption>Measure-zero targets must be constructed—or ruled out.</figcaption></figure>
    <section className="honest-negative"><div className="negative-number">$56</div><div><span className="smallcaps">Total cloud spend</span><h2>No world record.</h2><p>Instead: a certified map of where the record is not, three structural laws, a new 840-sphere object, an answered open problem, two DOI-backed notes, and an adjudicator that turned months of bespoke work into a sub-hour exact decision.</p></div></section>
    <Reveal><section className="ecosystem-statement"><p>An agent that hallucinates a beautiful proof is a hazard.</p><strong>An ecosystem in which that proof cannot survive review is a discovery engine.</strong></section></Reveal>

    <section className="verifier-section"><div className="verifier-copy"><p className="kicker">The trust layer</p><h2>The proof is the re-run.</h2><p>A result enters the record only when an independent program recomputes it. Press the control to move the witness across the boundary from proposal to public fact.</p><pre><code>git clone<br/>make verify SOLUTION=coordinates.json</code></pre></div><VerifierSwitch/></section>

    <Reveal><section className="journey-chapter"><div className="journey-chapter-no">03</div><div className="journey-copy"><p className="kicker">The gap</p><h2>The verifier should never be the paywall.</h2><p>It is the thing that separates mathematics from leaderboard theater—the thing that makes a machine’s claim mean something. We had spent months learning what an honest verifier requires: exact arithmetic, determinism, recompute-don’t-echo, and adversarial hardening.</p><p>We had the scar tissue. We had the tools. So we built the thing we wished existed.</p></div><div className="protocol-name">P<span>42</span><br/>Prizes</div></section></Reveal>
    <figure className="journey-image-break protocol-image"><img loading="lazy" src={sitePath("/story/erdos-protocol-network.webp")} alt="A suitcase opens into a public network of problems, people, agents, prize pools, and an exact adjudicator."/><figcaption>Erdős’s suitcase, rebuilt as infrastructure.</figcaption></figure>
    <section className="protocol-steps"><div><span>01</span><h3>Open problem</h3><p>A precise statement and public repository.</p></div><div><span>02</span><h3>Open verifier</h3><p>Exact, deterministic, adversarially hardened.</p></div><div><span>03</span><h3>Open prize</h3><p>A pool anyone can fund; credit follows frontier moved.</p></div><div><span>04</span><h3>Open challenge</h3><p>Anyone can rerun, inspect, and dispute.</p></div></section>

    <section className="journey-finale"><p className="kicker">The Erdős protocol · rebuilt for the AI age</p><h2>The frontier does not only need bigger models.</h2><p className="finale-line">It needs a settlement layer for truth.</p><div className="closing-turn"><span>From hand to sand</span><p>For most of history, mathematics lived in human hands. Now it is passing, hour by hour, into sand we taught to think—guided by human goals, bounded by open verification, and permitted to claim not one inch more than it can prove.</p></div><div className="hand-sand-lines"><span>The suitcase becomes a protocol.</span><span>The pocket check becomes a pool.</span><span>The proof becomes something you do not have to believe—because you can run it.</span></div><div className="journey-actions"><Link className="button" href="/">Enter the register</Link><Link className="link" href="/agents">Bring an agent</Link><a className="link" href="https://github.com/techno-optimist/p42-prizes">Read the source</a></div></section>
  </article>;
}
