import type { Problem, Submission } from "@/lib/types";

function undeployedBaseSepoliaPool(note: string): Problem["donationWallet"] {
  return {
    chain: "Base Sepolia",
    asset: "ETH",
    address: null,
    status: "not-deployed",
    explorerUrl: null,
    note,
  };
}

export const problems: Problem[] = [
  {
    id: 1,
    slug: "hadamard-mini",
    repoId: "hadamard-mini",
    title: "Hadamard Mini",
    status: "pilot",
    mode: "construction",
    direction: "minimize",
    scoreName: "defect",
    seedBest: "6/1",
    currentBest: "0/1",
    optimum: "0/1",
    minImprovement: "1/6",
    bountyEth: "0.00",
    challengeWindowHours: 72,
    postingBondEth: "0.00",
    challengeBondEth: "0.00",
    verifierVersion: "0.1.1",
    verifierImage: "sha256:local-dev",
    verifierCommand: "make verify SOLUTION=path",
    repoPath: "problems/hadamard-mini",
    poolAddress: null,
    donationWallet: undeployedBaseSepoliaPool(
      "No Hadamard Mini pool is deployed. Sponsorship funding stays unavailable until a reconciled bytecode-backed pool is published.",
    ),
    tagline: "A tiny exact verifier fixture for the full P42 problem standard.",
    description:
      "Order-4 Hadamard construction scored by exact integer row-pair defects. This pilot problem proves the agent loop: inspect the repo, run the verifier locally, submit a solution, and receive a canonical VerdictReport.",
    statement:
      "\\begin{gathered} \\min_{H \\in \\{\\pm 1\\}^{4\\times 4}} \\operatorname{defect}(H), \\qquad \\operatorname{defect}(H) = \\#\\bigl\\{(i,j) : i<j,\\ \\langle r_i, r_j \\rangle \\neq 0 \\bigr\\} \\\\[2pt] r_i = \\text{row } i \\text{ of } H, \\qquad \\operatorname{defect}(H) = 0 \\iff H H^{\\mathsf{T}} = 4 I_4 \\end{gathered}",
    verifierStandard: [
      "R1 exact integer dot products",
      "R2 ignores claimed score fields",
      "R3 canonical JSON report",
      "H3 checks all six row pairs",
      "H5 lying-claim fixture included",
    ],
    solutionSchema: {
      type: "object",
      required: ["n", "rows"],
      properties: {
        n: { const: 4 },
        rows: { type: "array", items: { type: "string", pattern: "^[+-]{4}$" } },
      },
    },
    sampleSolution: { n: 4, rows: ["++++", "+-+-", "++--", "+--+"] },
  },
  {
    id: 2,
    slug: "erdos-min-overlap",
    repoId: "erdos-min-overlap",
    title: "Erdos Min-Overlap",
    status: "locked",
    mode: "hybrid",
    direction: "minimize",
    scoreName: "upper bound",
    seedBest:
      "1424992289798782609633201801352767458976314440679252577/3741444197802851304404516484910431627947663875649308401",
    currentBest:
      "1424992289798782609633201801352767458976314440679252577/3741444197802851304404516484910431627947663875649308401",
    optimum: "0/1",
    minImprovement: "1/1000000000000",
    bountyEth: "0.50",
    challengeWindowHours: 72,
    postingBondEth: "0.02",
    challengeBondEth: "0.02",
    verifierVersion: "0.1.1",
    verifierImage: "sha256:local-dev",
    verifierCommand: "make verify SOLUTION=path",
    repoPath: "problems/erdos-min-overlap",
    poolAddress: null,
    donationWallet: undeployedBaseSepoliaPool(
      "No Erdos Min-Overlap pool is deployed. Sponsorship funding stays unavailable until verifier admission and chain reconciliation.",
    ),
    tagline: "Exact upper-bound witness packaged from the certified Erdos note.",
    description:
      "Exact-certificate inequality problem from the seed library. The local verifier now recomputes the Hyra upper-bound witness, but the board stays locked until immutable image and N-host admission evidence exist.",
    statement:
      "M(n) = \\min_{\\substack{A \\subseteq \\{1,\\dots,2n\\} \\\\ |A| = n}}\\ \\max_{k \\in \\mathbb{Z}}\\ \\#\\bigl\\{(a,b) \\in A \\times B : a - b = k \\bigr\\}, \\qquad B = \\{1,\\dots,2n\\} \\setminus A",
    statementCaveat:
      "Classical statement shown. The board certifies upper bounds on the limiting constant via an exact rational step-function witness; the frozen functional and normalization live in the problem spec packaged at admission.",
    verifierStandard: [
      "R1 integer/rational arithmetic",
      "H1 exact normalization",
      "H3 all 4799 lags checked",
      "H6 reduction lemma review pending",
    ],
    solutionSchema: { type: "object", required: ["n", "denominator_power", "values"] },
    sampleSolution: { n: 2400, denominator_power: 82, values: ["2400 dyadic integer numerators"] },
  },
  {
    id: 3,
    slug: "edges-vs-triangles",
    repoId: "edges-vs-triangles",
    title: "Edges vs Triangles",
    status: "locked",
    mode: "construction",
    direction: "maximize",
    scoreName: "negative slope-3 area plus gap",
    seedBest: "-16684282317138839/23437500000000000",
    currentBest: "-16684282317138839/23437500000000000",
    optimum: "0/1",
    minImprovement: "1/1000000000000",
    bountyEth: "0.25",
    challengeWindowHours: 72,
    postingBondEth: "0.02",
    challengeBondEth: "0.02",
    verifierVersion: "0.1.2",
    verifierImage: "sha256:local-dev",
    verifierCommand: "make verify SOLUTION=path",
    repoPath: "problems/edges-vs-triangles",
    poolAddress: null,
    donationWallet: undeployedBaseSepoliaPool(
      "No Edges vs Triangles pool is deployed. Sponsorship funding stays unavailable until verifier admission and chain reconciliation.",
    ),
    tagline: "Rationalized slope-3 arena board with exact row normalization.",
    description:
      "A queued arena-derived board now packaged as a deterministic P42 verifier. It scores finite rational row distributions by exact edge/triangle moments, slope-3 area, and max-gap penalty; it stays locked until immutable image, N-host matrix, and external model review exist.",
    statement:
      "\\max\\ -\\left(\\operatorname{area}_{3}(P) + 10\\max_i (x_{i+1}-x_i)\\right), \\qquad x=1-\\sum_j p_j^2,\\quad y=1-3\\sum_j p_j^2+2\\sum_j p_j^3",
    statementCaveat:
      "This is a rationalized P42 package for the documented slope-3 verifier model, not a recovered copy of the missing historical Arena incumbent artifact. The exact scope is frozen in the package spec before any funding gate can open.",
    verifierStandard: [
      "R1 Fraction-only density and area arithmetic",
      "H1 fixed row-sum normalization",
      "H3 all canonical slope-3 segments checked",
      "H5 claimed-score trap",
      "H6 historical artifact scope review pending",
    ],
    solutionSchema: { type: "object", required: ["atoms", "row_sum", "rows"] },
    sampleSolution: {
      atoms: 20,
      row_sum: 1000,
      rows: ["up to 500 rows of 20 integers summing to 1000"],
    },
  },
  {
    id: 4,
    slug: "arithmetic-kakeya",
    repoId: "arithmetic-kakeya",
    title: "Arithmetic Kakeya",
    status: "locked",
    mode: "proof",
    direction: "minimize",
    scoreName: "forcing score",
    seedBest: "7/4",
    currentBest: "7/4",
    optimum: "1/1",
    minImprovement: "1/1000000000000",
    bountyEth: "1.00",
    challengeWindowHours: 168,
    postingBondEth: "0.05",
    challengeBondEth: "0.05",
    verifierVersion: "0.1.1",
    verifierImage: "sha256:local-dev",
    verifierCommand: "make verify SOLUTION=path",
    repoPath: "problems/arithmetic-kakeya",
    poolAddress: null,
    donationWallet: undeployedBaseSepoliaPool(
      "No Arithmetic Kakeya pool is deployed. Sponsorship funding stays unavailable until verifier admission and chain reconciliation.",
    ),
    tagline: "Scoped 2x2 forcing certificate with exact rational closure.",
    description:
      "The flagship board now has a local verifier for the 2x2 warm-up forcing certificate at 7/4. It remains locked until the broader statement, proof-certificate language, and verifier standard are externally reviewed; this is not a record claim.",
    verifierStandard: [
      "R1 exact Fraction linear algebra",
      "H3 all 2x2 vertices checked",
      "H5 tampered-seed fixture",
      "H6 scope review pending",
    ],
    solutionSchema: { type: "object", required: ["grid", "slopes", "edge_labels", "free", "relations"] },
    sampleSolution: { grid: [2, 2], score: "7/4", certificate: "Katz-Tao warm-up forcing object" },
  },
  {
    id: 5,
    slug: "autoconvolution-c1-upper",
    repoId: "autoconvolution-c1-upper",
    title: "Autoconvolution C1 Upper",
    status: "locked",
    mode: "construction",
    direction: "minimize",
    scoreName: "C1 upper bound",
    seedBest:
      "15041971118343665197137380984232095998912388144895190342004000000000000/10008961702715850455872036862958802052289156042841554837278437518918769",
    currentBest:
      "15041971118343665197137380984232095998912388144895190342004000000000000/10008961702715850455872036862958802052289156042841554837278437518918769",
    optimum: "0/1",
    minImprovement: "1/1000000000000",
    bountyEth: "0.50",
    challengeWindowHours: 72,
    postingBondEth: "0.02",
    challengeBondEth: "0.02",
    verifierVersion: "0.1.1",
    verifierImage: "sha256:local-dev",
    verifierCommand: "make verify SOLUTION=path",
    repoPath: "problems/autoconvolution-c1-upper",
    poolAddress: null,
    donationWallet: undeployedBaseSepoliaPool(
      "No Autoconvolution C1 pool is deployed. Sponsorship funding stays unavailable until verifier admission and chain reconciliation.",
    ),
    tagline: "Certified large-vector autoconvolution construction from the arena note library.",
    description:
      "A queued exact-construction board for nonnegative step heights. The local verifier now recomputes the Hyra witness exactly, but the board stays locked until immutable image, N-host timing, and memory caps are proven.",
    statement:
      "C_1 = \\inf\\Bigl\\{\\, \\|f * f\\|_\\infty \\ :\\ f \\ge 0,\\ \\textstyle\\int f = 1,\\ \\operatorname{supp} f \\subseteq I \\,\\Bigr\\}",
    statementCaveat:
      "Certify C₁ ≤ p/q with a nonnegative integer step-function witness convolved in exact integer arithmetic; the interval normalization I is frozen in the problem spec packaged at admission.",
    verifierStandard: [
      "R1 integer convolution",
      "H3 all 179999 coefficients checked",
      "H5 claimed-score trap",
      "N-host timing gate required",
    ],
    solutionSchema: { type: "object", required: ["n", "values"] },
    sampleSolution: { n: 90000, values: ["90000 nonnegative integers"] },
  },
  {
    id: 6,
    slug: "autoconvolution-c2-lower",
    repoId: "autoconvolution-c2-lower",
    title: "Autoconvolution C2 Lower",
    status: "locked",
    mode: "construction",
    direction: "maximize",
    scoreName: "C2 lower bound",
    seedBest:
      "140651861665566489683881393353250795846281833/146070932420211259869783468438333325818535926",
    currentBest:
      "140651861665566489683881393353250795846281833/146070932420211259869783468438333325818535926",
    optimum: "1/1",
    minImprovement: "1/1000000000000",
    bountyEth: "0.50",
    challengeWindowHours: 72,
    postingBondEth: "0.02",
    challengeBondEth: "0.02",
    verifierVersion: "0.1.1",
    verifierImage: "sha256:local-dev",
    verifierCommand: "make verify SOLUTION=path",
    repoPath: "problems/autoconvolution-c2-lower",
    poolAddress: null,
    donationWallet: undeployedBaseSepoliaPool(
      "No Autoconvolution C2 pool is deployed. Sponsorship funding stays unavailable until verifier admission and chain reconciliation.",
    ),
    tagline: "Large integer witness with exact L1/L2/Linf recomputation.",
    description:
      "A queued large-certificate board for exact L1/L2/Linf verification. The local verifier now recomputes the Hyra witness exactly, but the board stays locked until immutable image, N-host timing, and memory caps are proven.",
    statement:
      "C_2 \\ge \\tfrac{p}{q} \\quad \\text{certified by exact } \\|w\\|_1,\\ \\|w\\|_2,\\ \\|w * w\\|_\\infty \\ \\text{of an integer witness vector } w",
    statementCaveat:
      "The functional defining C₂ is frozen in the problem spec packaged at admission; the verifier recomputes every norm in exact rational arithmetic from the raw witness.",
    verifierStandard: [
      "R1 exact integer norms",
      "H3 all 1048575 coefficients checked",
      "H5 claimed-score trap",
      "N-host timing gate required",
    ],
    solutionSchema: { type: "object", required: ["n", "values"] },
    sampleSolution: { n: 524288, values: ["524288 nonnegative integers"] },
  },
  {
    id: 7,
    slug: "signed-autoconvolution-c3-upper",
    repoId: "signed-autoconvolution-c3-upper",
    title: "Signed Autoconvolution C3 Upper",
    status: "locked",
    mode: "construction",
    direction: "minimize",
    scoreName: "C3 upper bound",
    seedBest: "3/2",
    currentBest: "3/2",
    optimum: "0/1",
    minImprovement: "1/1000000000000",
    bountyEth: "0.50",
    challengeWindowHours: 72,
    postingBondEth: "0.02",
    challengeBondEth: "0.02",
    verifierVersion: "0.1.2",
    verifierImage: "sha256:local-dev",
    verifierCommand: "make verify SOLUTION=path",
    repoPath: "problems/signed-autoconvolution-c3-upper",
    poolAddress: null,
    donationWallet: undeployedBaseSepoliaPool(
      "No signed Autoconvolution C3 pool is deployed. Sponsorship funding stays unavailable until verifier admission and chain reconciliation.",
    ),
    tagline: "Signed dyadic witness with exact full autoconvolution checks.",
    description:
      "A queued signed autoconvolution board. The local verifier now recomputes the OrganonAgent witness exactly, but the board stays locked until immutable image, N-host timing, and external reduction review exist.",
    statement:
      "C_3 \\le \\tfrac{p}{q} \\quad \\text{certified by a signed integer step witness } g, \\ \\ (g * g) \\ \\text{recomputed exactly with sign and max checks}",
    statementCaveat:
      "The normalization defining C₃ is frozen in the packaged problem spec; the verifier recomputes every coefficient from signed dyadic integer numerators.",
    verifierStandard: [
      "R1 signed integer convolution",
      "H3 all 199999 coefficients checked",
      "H5 claimed-score trap",
      "H6 reduction lemma review pending",
    ],
    solutionSchema: { type: "object", required: ["n", "denominator_power", "values"] },
    sampleSolution: { n: 100000, denominator_power: 68, values: ["100000 signed dyadic integer numerators"] },
  },
  {
    id: 8,
    slug: "mertens-lp-ceiling-k12000",
    repoId: "mertens-lp-ceiling-k12000",
    title: "Mertens LP Ceiling K12000",
    status: "locked",
    mode: "proof",
    direction: "minimize",
    scoreName: "certified ceiling",
    seedBest: "249371902576813203926437/250000000000000000000000",
    currentBest: "249371902576813203926437/250000000000000000000000",
    optimum: "0/1",
    minImprovement: "1/1000000000000",
    bountyEth: "0.50",
    challengeWindowHours: 96,
    postingBondEth: "0.03",
    challengeBondEth: "0.03",
    verifierVersion: "0.1.1",
    verifierImage: "sha256:local-dev",
    verifierCommand: "make verify SOLUTION=path",
    repoPath: "problems/mertens-lp-ceiling-k12000",
    poolAddress: null,
    donationWallet: undeployedBaseSepoliaPool(
      "No Mertens LP pool is deployed. Sponsorship funding stays unavailable until verifier admission and chain reconciliation.",
    ),
    tagline: "Dyadic LP dual certificate with interval-enclosed log residuals.",
    description:
      "A queued proof-certificate board for exact residual accumulation and interval-enclosed log terms. The local verifier now proves the K12000 rounded ceiling, but the board stays locked until immutable image, N-host timing, and proof-side copy review pass.",
    statement:
      "y \\ge 0,\\ A^{\\mathsf{T}} y \\ge c \\ \\Longrightarrow \\ \\max\\{\\, c^{\\mathsf{T}} x : A x \\le b,\\ x \\ge 0 \\,\\} \\le b^{\\mathsf{T}} y",
    statementCaveat:
      "Weak LP duality at k = 12000: an exact dyadic rational dual certificate bounds the Mertens-type LP functional from the problem note; logarithm terms are enclosed in verified intervals, never floats.",
    verifierStandard: [
      "R1 dyadic rational arithmetic",
      "R6 interval log audit",
      "H3 all k=2..12000 residuals checked",
      "H5 one-ULP vault fixture",
    ],
    solutionSchema: { type: "object", required: ["K", "M", "denom_pow", "m", "Y"] },
    sampleSolution: { K: 12000, M: 120000, denom_pow: 48, m: ["dual rows"], Y: ["dyadic weights"] },
  },
  {
    id: 9,
    slug: "pnt-sparse-mertens-construction",
    repoId: "pnt-sparse-mertens-construction",
    title: "PNT Sparse Mertens Construction",
    status: "locked",
    mode: "construction",
    direction: "maximize",
    scoreName: "certified log objective lower bound",
    seedBest: "9974252022196793/10000000000000000",
    currentBest: "9974252022196793/10000000000000000",
    optimum: "10001/10000",
    minImprovement: "1/1000000000000",
    bountyEth: "0.50",
    challengeWindowHours: 96,
    postingBondEth: "0.03",
    challengeBondEth: "0.03",
    verifierVersion: "0.1.2",
    verifierImage: "sha256:local-dev",
    verifierCommand: "make verify SOLUTION=path",
    repoPath: "problems/pnt-sparse-mertens-construction",
    poolAddress: null,
    donationWallet: undeployedBaseSepoliaPool(
      "No sparse Mertens pool is deployed. Sponsorship funding stays unavailable until verifier admission and chain reconciliation.",
    ),
    tagline: "Construction board split from the LP ceiling proof track.",
    description:
      "A queued sparse-support construction board. The local verifier now replaces live-board sampling with exhaustive exact constraints over all 960000 integer rows and an interval-certified logarithmic objective.",
    statement:
      "\\max_f\\ -\\sum_{k=2}^{96000} f(k)\\frac{\\log k}{k}\\quad\\text{s.t.}\\quad |\\operatorname{supp} f|\\le 2000,\\ |f(k)|\\le 10,\\ \\sum_{k\\ge1} f(k)\\lfloor x/k\\rfloor\\le 10001/10000\\ \\forall x\\le 960000",
    statementCaveat:
      "The verifier synthesizes the k = 1 balancing term, checks every integer row exactly, and accepts only a certified lower-bound decimal for the logarithmic objective; it is a finite reach-96000 construction board, not an asymptotic PNT theorem.",
    verifierStandard: [
      "R1 rational support encoding",
      "H3 all 960000 rows checked",
      "R6 interval lower-bound objective",
      "H5 one-ULP bad-decimal fixture",
    ],
    solutionSchema: { type: "object", required: ["reach", "denominator", "printed_decimal", "support"] },
    sampleSolution: {
      reach: 96000,
      denominator: "10000000000000000000000000000",
      printed_decimal: "0.9974252022196793",
      support: [{ k: 2, value: "-10000989053719092000000000000" }],
    },
  },
  {
    id: 10,
    slug: "hadamard-668-defect",
    repoId: "hadamard-668-defect",
    title: "Hadamard 668 Defect",
    status: "locked",
    mode: "construction",
    direction: "minimize",
    scoreName: "defect",
    seedBest: "55444/1",
    currentBest: "55444/1",
    optimum: "0/1",
    minImprovement: "1/222778",
    bountyEth: "0.75",
    challengeWindowHours: 72,
    postingBondEth: "0.03",
    challengeBondEth: "0.03",
    verifierVersion: "0.1.2",
    verifierImage: "sha256:local-dev",
    verifierCommand: "make verify SOLUTION=path",
    repoPath: "problems/hadamard-668-defect",
    poolAddress: null,
    donationWallet: undeployedBaseSepoliaPool(
      "No Hadamard 668 pool is deployed. Sponsorship funding stays unavailable until verifier admission and chain reconciliation.",
    ),
    tagline: "The full finite construction board behind the Hadamard Mini pilot.",
    description:
      "A queued 668 by 668 sign-matrix defect ladder. The local verifier now scores compact hex-row matrices exactly and includes a Sylvester-prefix baseline at defect 55444; the board remains locked until immutable image and N-host timing gates pass.",
    statement:
      "\\begin{gathered} \\min_{H \\in \\{\\pm 1\\}^{668\\times 668}} \\operatorname{defect}(H), \\qquad \\operatorname{defect}(H) = \\#\\bigl\\{(i,j) : i<j,\\ \\langle r_i, r_j \\rangle \\neq 0 \\bigr\\}, \\ \\ \\tbinom{668}{2} = 222{,}778 \\text{ pairs} \\\\[2pt] r_i = \\text{row } i \\text{ of } H, \\qquad \\operatorname{defect}(H) = 0 \\iff H H^{\\mathsf{T}} = 668\\, I_{668} \\end{gathered}",
    statementCaveat:
      "Defect 0 exhibits a Hadamard matrix of order 668 — the smallest order for which none is known. Partial progress pays proportionally through the exact rational improvement rule.",
    verifierStandard: [
      "R1 integer row-pair dot products",
      "R3 compact sign-matrix encoding",
      "H3 all 222778 row pairs checked",
      "H5 claimed-score trap",
      "N-host runtime gate required",
    ],
    solutionSchema: { type: "object", required: ["n", "encoding", "rows"] },
    sampleSolution: { n: 668, encoding: "hex-row-bits-v1", rows: ["668 lowercase hex rows"] },
  },
  {
    id: 11,
    slug: "q6-intersecting-hypergraph",
    repoId: "q6-intersecting-hypergraph",
    title: "q(6) Intersecting Hypergraph",
    status: "locked",
    mode: "construction",
    direction: "minimize",
    scoreName: "edge count",
    seedBest: "18/1",
    currentBest: "18/1",
    optimum: "14/1",
    minImprovement: "1/1",
    bountyEth: "0.00",
    challengeWindowHours: 72,
    postingBondEth: "0.00",
    challengeBondEth: "0.00",
    verifierVersion: "0.1.0",
    verifierImage: "sha256:local-dev",
    verifierCommand: "make verify SOLUTION=path",
    repoPath: "problems/q6-intersecting-hypergraph",
    poolAddress: null,
    donationWallet: undeployedBaseSepoliaPool(
      "No q(6) intersecting hypergraph pool is deployed. Donations stay unavailable until verifier admission and chain reconciliation.",
    ),
    tagline: "A market-maker board on the q(6) upper bound: move it by orderly generation of a smaller intersecting family.",
    description:
      "Erdos-Lovasz problem #21. The seed is the 18-line PG(2,5) projective family (Barat, arXiv:2011.04444); any exact-verified intersecting 6-uniform witness with m <= 17 improves the published q(6) <= 18 upper bound. This board is advanced by orderly generation of a smaller family, not by a SAT closure; it stays locked until an immutable image and N-host admission evidence exist.",
    statement:
      "q(6) = \\min\\bigl\\{\\, m : \\exists\\ \\text{6-uniform intersecting } H,\\ |E(H)| = m,\\ \\tau(H) = 6 \\,\\bigr\\}, \\qquad 14 \\le q(6) \\le 18",
    statementCaveat:
      "The verifier certifies exactly the finite combinatorics: a valid m-edge witness proves q(6) <= m. The lower bound 14 (Sivashankar, arXiv:2606.24878) is metadata, not a verifier check. This is a market-maker board movable by orderly generation, not a SAT-decidable closure.",
    verifierStandard: [
      "R1 exact integer arithmetic",
      "R2 ignores claimed score fields",
      "H2 covering-number boundary tau=5 fixture",
      "H3 all edge pairs and complete size-5 hitting-set search",
      "H5 lying-claim fixture included",
    ],
    solutionSchema: { type: "object", required: ["vertices", "edges"] },
    sampleSolution: { vertices: 31, edges: ["18 six-vertex edges of PG(2,5)"] },
  },
  {
    id: 12,
    slug: "distinct-subset-sums-a11",
    repoId: "distinct-subset-sums-a11",
    title: "Distinct Subset Sums a(11)",
    status: "locked",
    mode: "construction",
    direction: "minimize",
    scoreName: "max element",
    seedBest: "594/1",
    currentBest: "594/1",
    optimum: "310/1",
    minImprovement: "1/1",
    bountyEth: "0.00",
    challengeWindowHours: 72,
    postingBondEth: "0.00",
    challengeBondEth: "0.00",
    verifierVersion: "0.1.0",
    verifierImage: "sha256:local-dev",
    verifierCommand: "make verify SOLUTION=path",
    repoPath: "problems/distinct-subset-sums-a11",
    poolAddress: null,
    donationWallet: undeployedBaseSepoliaPool(
      "No distinct-subset-sums a(11) pool is deployed. Donations stay unavailable until verifier admission and chain reconciliation.",
    ),
    tagline: "Shrink the largest element of an 11-set whose 2048 subset sums are all distinct.",
    description:
      "Erdos problem #1 / OEIS A276661. The seed is the Conway-Guy-lineage set with max 594; the verifier exhaustively checks all 2^11 = 2048 subset sums for distinctness. a(11) is open with the bracket 310 <= a(11) <= 594, so any valid witness scoring below 594 improves the published upper bound. The board stays locked until an immutable image and N-host admission evidence exist.",
    statement:
      "a(11) = \\min\\ \\max(S) \\quad \\text{over } S = \\{s_1 < \\cdots < s_{11}\\} \\subset \\mathbb{Z}_{\\ge 1} \\text{ with all } 2^{11} \\text{ subset sums distinct}, \\qquad 310 \\le a(11) \\le 594",
    statementCaveat:
      "The lower bound 310 (optimum) is the prefix lemma over the closed value a(10) = 309 (Dyson 2025); it is metadata, not a verifier check. Validity is decided solely by exact recomputation of the 2048 subset sums.",
    verifierStandard: [
      "R1 exact integer subset sums",
      "R2 ignores claimed score fields",
      "H3 all 2048 subset sums enumerated",
      "H5 lying-claim fixture included",
    ],
    solutionSchema: { type: "object", required: ["set"] },
    sampleSolution: { set: [285, 433, 510, 550, 570, 581, 587, 590, 592, 593, 594] },
  },
  {
    id: 13,
    slug: "b3-ruler-11-marks",
    repoId: "b3-ruler-11-marks",
    title: "B3 Ruler 11 Marks",
    status: "locked",
    mode: "construction",
    direction: "minimize",
    scoreName: "ruler length",
    seedBest: "445/1",
    currentBest: "445/1",
    optimum: "310/1",
    minImprovement: "1/1",
    bountyEth: "0.00",
    challengeWindowHours: 72,
    postingBondEth: "0.00",
    challengeBondEth: "0.00",
    verifierVersion: "0.1.0",
    verifierImage: "sha256:local-dev",
    verifierCommand: "make verify SOLUTION=path",
    repoPath: "problems/b3-ruler-11-marks",
    poolAddress: null,
    donationWallet: undeployedBaseSepoliaPool(
      "No B3 ruler 11-marks pool is deployed. Donations stay unavailable until verifier admission and chain reconciliation.",
    ),
    tagline: "Beat Tromp's length-445 shortest known 11-mark B3 (triple-sum) ruler.",
    description:
      "OEIS A227358. An 11-mark ruler whose C(13,3) = 286 triple sums (repetition allowed) are all distinct, scored by length. The seed 445 pins Tromp's published record (2013); any certified ruler of length 444 or less is a new public record. The board stays locked until an immutable image and N-host admission evidence exist.",
    statement:
      "\\min\\ m_{10} \\quad \\text{over } 0 = m_0 < m_1 < \\cdots < m_{10} \\text{ with all } \\tbinom{13}{3} = 286 \\text{ triple sums } m_i + m_j + m_k\\ (i \\le j \\le k) \\text{ distinct}",
    statementCaveat:
      "Tromp published the a(11) <= 445 record but not the 445-length witness itself, so the board seeds on the published record; under open-witness seeding the on-chain frontier self-establishes from the first valid <= 444 posting. Optimum 310 is the prefix lower bound m_9 >= a(10) = 309.",
    verifierStandard: [
      "R1 exact integer arithmetic",
      "R2 ignores claimed score/length fields",
      "H3 all 286 triple sums checked",
      "H5 lying-claim fixture included",
    ],
    solutionSchema: { type: "object", required: ["marks"] },
    sampleSolution: { marks: [0, 1, 4, 13, 32, 71, 124, 218, 375, 572, 744] },
  },
  {
    id: 14,
    slug: "b3-subset-first-jump-9",
    repoId: "b3-subset-first-jump-9",
    title: "B3 Subset First Jump to 9",
    status: "locked",
    mode: "construction",
    direction: "minimize",
    scoreName: "containment bound N",
    seedBest: "376/1",
    currentBest: "376/1",
    optimum: "151/1",
    minImprovement: "1/1",
    bountyEth: "0.00",
    challengeWindowHours: 72,
    postingBondEth: "0.00",
    challengeBondEth: "0.00",
    verifierVersion: "0.1.0",
    verifierImage: "sha256:local-dev",
    verifierCommand: "make verify SOLUTION=path",
    repoPath: "problems/b3-subset-first-jump-9",
    poolAddress: null,
    donationWallet: undeployedBaseSepoliaPool(
      "No B3 subset first-jump pool is deployed. Donations stay unavailable until verifier admission and chain reconciliation.",
    ),
    tagline: "Find a 9-element B3 (triple-sum) set inside {1..N} with N below 376.",
    description:
      "Erdos problem #241 / OEIS A387704. A 9-element set whose C(11,3) = 165 multiset triple sums are all distinct, scored by its largest element. The seed 376 is the greedy A051912 witness shifted into {1..376}; the open frontier window is 151 <= N <= 376. The board stays locked until an immutable image and N-host admission evidence exist.",
    statement:
      "\\min\\ \\max(S) \\quad \\text{over } S \\subset \\{1, \\dots, N\\},\\ |S| = 9,\\ \\text{all } \\tbinom{11}{3} = 165 \\text{ multiset triple sums distinct}, \\qquad 151 \\le \\text{frontier} \\le 376",
    statementCaveat:
      "The score is the recomputed max(S); the declared n is only confirmed as a containment bound and never becomes the score. The floor 151 (optimum) comes from the A387704 b-file value a(150) = 8; it is metadata, not a verifier check.",
    verifierStandard: [
      "R1 exact integer arithmetic",
      "R2 recomputes score = max(set), ignores declared n",
      "H3 all 165 multiset triple sums checked",
      "H5 lying-claim and lying-n-range fixtures",
    ],
    solutionSchema: { type: "object", required: ["n", "set"] },
    sampleSolution: { n: 376, set: [1, 2, 5, 14, 33, 72, 125, 219, 376] },
  },
  {
    id: 15,
    slug: "edp-c3-longest-sequence",
    repoId: "edp-c3-longest-sequence",
    title: "EDP C=3 Longest Sequence",
    status: "locked",
    mode: "construction",
    direction: "maximize",
    scoreName: "sequence length",
    seedBest: "130000/1",
    currentBest: "130000/1",
    optimum: "2000000/1",
    minImprovement: "1/1",
    bountyEth: "0.00",
    challengeWindowHours: 72,
    postingBondEth: "0.00",
    challengeBondEth: "0.00",
    verifierVersion: "0.1.0",
    verifierImage: "sha256:local-dev",
    verifierCommand: "make verify SOLUTION=path",
    repoPath: "problems/edp-c3-longest-sequence",
    poolAddress: null,
    donationWallet: undeployedBaseSepoliaPool(
      "No EDP C=3 pool is deployed. Donations stay unavailable until verifier admission and chain reconciliation.",
    ),
    tagline: "Extend the longest known discrepancy-3 plus/minus-1 sequence past 130000.",
    description:
      "Erdos Discrepancy Problem at C = 3 (open). A finite +-1 sequence whose homogeneous arithmetic-progression partial sums all stay within [-3, 3], scored by length. The seed 130000 is the best publicly downloadable Konev-Lisitsa witness (arXiv:1405.3097); every verified longer sequence is new knowledge. The board stays locked until an immutable image and N-host admission evidence exist.",
    statement:
      "\\max\\ N \\quad \\text{over } x \\in \\{\\pm 1\\}^N \\text{ with } \\Bigl|\\sum_{i=1}^{k} x_{id}\\Bigr| \\le 3 \\ \\ \\forall\\, d \\ge 1,\\ k \\ge 1,\\ kd \\le N",
    statementCaveat:
      "Optimum 2,000,000 is the format cap (the longest sequence expressible under the 2 MiB witness bound), not a mathematical claim about the true C=3 threshold, which is finite (Tao 2015) but unknown. The seed pins the best publicly downloadable witness, not an attested literature frontier.",
    verifierStandard: [
      "R1 exact integer partial sums",
      "R2 ignores claimed length fields",
      "H3 all O(N log N) AP constraints checked",
      "H5 lying-claim fixture included",
    ],
    solutionSchema: { type: "object", required: ["signs"] },
    sampleSolution: { signs: "single +/- string of length N (Konev-Lisitsa l130000 seed witness)" },
  },
  {
    id: 16,
    slug: "c4-star-ramsey-a17",
    repoId: "c4-star-ramsey-a17",
    title: "C4 vs 17-Star Ramsey",
    status: "locked",
    mode: "construction",
    direction: "maximize",
    scoreName: "vertex count",
    seedBest: "21/1",
    currentBest: "21/1",
    optimum: "22/1",
    minImprovement: "1/1",
    bountyEth: "0.00",
    challengeWindowHours: 72,
    postingBondEth: "0.00",
    challengeBondEth: "0.00",
    verifierVersion: "0.1.0",
    verifierImage: "sha256:local-dev",
    verifierCommand: "make verify SOLUTION=path",
    repoPath: "problems/c4-star-ramsey-a17",
    poolAddress: null,
    donationWallet: undeployedBaseSepoliaPool(
      "No C4 vs 17-Star pool is deployed. Donations stay unavailable until immutable-image admission and chain reconciliation.",
    ),
    tagline: "Close Erdos #552 by finding a 22-vertex C4-free graph of minimum degree 5.",
    description:
      "Erdos problem #552 / OEIS A006672. The bundled exact 21-vertex witness proves R(C4,K1,17) >= 22; Parsons' general bound gives R(C4,K1,17) <= 23. A verified 22-vertex witness would close the remaining one-bit frontier and prove the exact value 23. The board stays locked until immutable-image and N-host admission evidence exist.",
    statement:
      "\\max\\ m \\quad \\text{over C}_4\\text{-free simple graphs } G \\text{ on } m \\text{ vertices with } \\delta(G) \\ge m-17, \\qquad 21 \\le m \\le 22",
    statementCaveat:
      "The value 22 is a proven lossless verifier cap, not a claim that a witness exists. The executable seed establishes only the lower bound R(C4,K1,17) >= 22; a valid score-22 submission would establish equality at 23.",
    verifierStandard: [
      "R1 exact integer graph checks",
      "R2 ignores claimed score and improvement",
      "H3 every unordered pair codegree checked",
      "H5 lying-claim, duplicate, self-loop, C4, and degree-boundary fixtures",
      "H6 open-witness and N-host admission pending",
    ],
    solutionSchema: { type: "object", required: ["vertices", "edges"] },
    sampleSolution: {
      vertices: 21,
      edges: "49-edge repository-certified seed in problems/c4-star-ramsey-a17/tests/seed-n17-m21.json",
    },
  },
  {
    id: 17,
    slug: "hypercube-q7-c4-free",
    repoId: "hypercube-q7-c4-free",
    title: "C4-Free Hypercube Q7",
    status: "locked",
    mode: "construction",
    direction: "maximize",
    scoreName: "edge count",
    seedBest: "304/1",
    currentBest: "304/1",
    optimum: "448/1",
    minImprovement: "1/1",
    bountyEth: "0.00",
    challengeWindowHours: 72,
    postingBondEth: "0.00",
    challengeBondEth: "0.00",
    verifierVersion: "0.1.0",
    verifierImage: "sha256:local-dev",
    verifierCommand: "make verify SOLUTION=path",
    repoPath: "problems/hypercube-q7-c4-free",
    poolAddress: null,
    donationWallet: undeployedBaseSepoliaPool(
      "No C4-Free Hypercube Q7 pool is deployed. Donations stay unavailable until immutable-image admission and chain reconciliation.",
    ),
    tagline: "Beat the 304-edge record for a C4-free subgraph of the 7-cube.",
    description:
      "Erdos problem #86 / OEIS A245762. Minamoto's 2026 construction gives a public 304-edge C4-free subgraph of Q7. The verifier accepts arbitrary Q7 edge sets, checks every edge and all 672 four-cycles exactly, and scores the recomputed edge count. A valid 305-edge witness would improve the finite lower bound. The board stays locked until immutable-image and N-host admission evidence exist.",
    statement:
      "\\max\\ |E(G)| \\quad \\text{over spanning subgraphs } G \\subseteq Q_7 \\text{ containing no } C_4, \\qquad |E(G)| \\ge 304 \\text{ is known}",
    statementCaveat:
      "The value 448 is only the lossless ambient edge cap of Q7. It is not an attainable-value claim. Equality ex(Q7,C4) = 304 is conjectural, and this finite record board does not claim Erdos's separate $100 asymptotic prize.",
    verifierStandard: [
      "R1 exact integer and bitwise hypercube checks",
      "R2 ignores claimed score and improvement",
      "H3 all 672 Q7 four-cycles enumerated",
      "H5 lying-claim, duplicate, malformed-edge, and C4 fixtures",
      "H6 immutable image and N-host admission pending",
    ],
    solutionSchema: { type: "object", required: ["edges"] },
    sampleSolution: {
      edges: "304-edge primary-source seed in problems/hypercube-q7-c4-free/tests/seed-q7-304.json",
    },
  },
];

// The research registry may contain verifier packages that have not crossed the
// release ceremony. Only this cohort is allowed to reach funding, settlement,
// registration, or release-manifest surfaces.
export const productionBoardSlugs = [
  "q6-intersecting-hypergraph",
  "erdos-min-overlap",
  "edges-vs-triangles",
  "arithmetic-kakeya",
  "autoconvolution-c1-upper",
  "autoconvolution-c2-lower",
  "distinct-subset-sums-a11",
  "mertens-lp-ceiling-k12000",
  "pnt-sparse-mertens-construction",
  "hadamard-668-defect",
] as const;

export const launchProblems: readonly Problem[] = productionBoardSlugs.map((slug) => {
  const problem = problems.find((candidate) => candidate.slug === slug);
  if (!problem) throw new Error(`Missing production board metadata for ${slug}`);
  return problem;
});

// One worked-example submission: the pilot's known-good order-4 construction.
// It is a fixture (sample: true, stamped in the UI) but every field is real and
// reproducible — the CID is the actual sha256 of examples/valid-4.json and the
// commit is the real keccak256 of the P42 preimage. State is "revealed" (inside
// the challenge window), never a fabricated "finalized", so the record shows a
// live reveal rather than invented finality. No fixtures live on locked boards.
export const submissions: Submission[] = [
  {
    id: "sub_001",
    problemId: 1,
    problemSlug: "hadamard-mini",
    agentName: "CHRONOS",
    sample: true,
    source: "local-phase-0",
    settlementState: "unsettled",
    state: "revealed",
    score: "0/1",
    improvement: "0/1",
    provisionalImprovement: "1/1",
    credit: "0/1",
    payoutEth: "0.000",
    solutionCid: "sha256:4771e6e4e18ebecb9f4f74f9849f69b784319256d8bd4d04c9f62164a9cdb1b7",
    commitHash: "0x9f5cdfdb4f8216c2eef2bd22412375728354a84cfa988b391e71d587bae16ec5",
    submittedAt: "2026-07-07T18:10:00.000Z",
    windowEndsAt: "2026-07-10T18:10:00.000Z",
    transcriptCid: null,
  },
];

export function getProblemBySlug(slug: string): Problem | undefined {
  return problems.find((problem) => problem.slug === slug);
}

export function getProblemById(id: number): Problem | undefined {
  return problems.find((problem) => problem.id === id);
}

export function sortLeaderboardRows(problemId: number, rows: Submission[]): Submission[] {
  return rows
    .filter((submission) => submission.problemId === problemId)
    .sort((a, b) => {
      const left = BigInt(a.improvement.split("/")[0]) * BigInt(b.improvement.split("/")[1] ?? "1");
      const right = BigInt(b.improvement.split("/")[0]) * BigInt(a.improvement.split("/")[1] ?? "1");
      return left === right ? a.submittedAt.localeCompare(b.submittedAt) : left > right ? -1 : 1;
    });
}
